apiVersion: v1
kind: ConfigMap
metadata:
  name: tvshows-db-config
  namespace: kiii
data:
  POSTGRES_DB: tvshows
  POSTGRES_USER: postgres

---

apiVersion: v1
kind: Secret
metadata:
  name: tvshows-db-secret
  namespace: kiii
data:
  password: YWRtaW4=

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: kiii
  labels:
    app: postgres
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tvshows-db-dep
  namespace: kiii
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        namespace: kiii
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: tvshows-db-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tvshows-db-secret
                  key: password
          ports:
            - containerPort: 5432
              name: db-port
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-volume-mount
      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---

apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: kiii
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
