kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: kiii
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
  name: postgres-pv-claim
  namespace: kiii
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
